// Multi-Language Backend Support - Generate backends in Python, Go, and more

export interface BackendTemplate {
  language: 'python' | 'go' | 'rust' | 'node';
  framework: string;
  files: { path: string; content: string; language: string }[];
}

// Python FastAPI Backend Template
export function generatePythonFastAPIBackend(projectName: string, features: string[] = []): BackendTemplate {
  const hasAuth = features.includes('auth');
  const hasDatabase = features.includes('database');
  
  const files: { path: string; content: string; language: string }[] = [];
  
  // requirements.txt
  const requirements = [
    'fastapi==0.109.0',
    'uvicorn[standard]==0.27.0',
    'python-dotenv==1.0.0'
  ];
  
  if (hasAuth) {
    requirements.push('python-jose[cryptography]==3.3.0', 'passlib[bcrypt]==1.7.4');
  }
  
  if (hasDatabase) {
    requirements.push('sqlalchemy==2.0.25', 'databases==0.8.0', 'asyncpg==0.29.0');
  }
  
  files.push({
    path: 'requirements.txt',
    content: requirements.join('\n'),
    language: 'text'
  });
  
  // main.py
  files.push({
    path: 'main.py',
    content: `"""${projectName} - FastAPI Backend"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
import os
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(
    title="${projectName}",
    description="Auto-generated API backend",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory storage
items_db: dict = {}
item_counter = 0

# Models
class ItemCreate(BaseModel):
    name: str
    description: Optional[str] = None
    
class Item(ItemCreate):
    id: int
    created_at: datetime

# Routes
@app.get("/")
async def root():
    return {"message": "Welcome to ${projectName} API", "version": "1.0.0"}

@app.get("/health")
async def health_check():
    return {"status": "healthy", "timestamp": datetime.now().isoformat()}

@app.post("/api/items", response_model=Item)
async def create_item(item: ItemCreate):
    global item_counter
    item_counter += 1
    new_item = Item(
        id=item_counter,
        name=item.name,
        description=item.description,
        created_at=datetime.now()
    )
    items_db[item_counter] = new_item
    return new_item

@app.get("/api/items", response_model=List[Item])
async def list_items():
    return list(items_db.values())

@app.get("/api/items/{item_id}", response_model=Item)
async def get_item(item_id: int):
    if item_id not in items_db:
        raise HTTPException(status_code=404, detail="Item not found")
    return items_db[item_id]

@app.put("/api/items/{item_id}", response_model=Item)
async def update_item(item_id: int, item: ItemCreate):
    if item_id not in items_db:
        raise HTTPException(status_code=404, detail="Item not found")
    existing = items_db[item_id]
    updated = Item(
        id=item_id,
        name=item.name,
        description=item.description,
        created_at=existing.created_at
    )
    items_db[item_id] = updated
    return updated

@app.delete("/api/items/{item_id}")
async def delete_item(item_id: int):
    if item_id not in items_db:
        raise HTTPException(status_code=404, detail="Item not found")
    del items_db[item_id]
    return {"message": "Item deleted successfully"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", 8000)))
`,
    language: 'python'
  });
  
  // Dockerfile
  files.push({
    path: 'Dockerfile',
    content: `FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`,
    language: 'dockerfile'
  });
  
  // .env.example
  files.push({
    path: '.env.example',
    content: `# Environment Variables
PORT=8000
DATABASE_URL=postgresql://user:pass@localhost/db
SECRET_KEY=your-secret-key-here
`,
    language: 'text'
  });
  
  // README.md
  files.push({
    path: 'README.md',
    content: `# ${projectName}

Python FastAPI backend generated by AutoCoder.

## Getting Started

\`\`\`bash
# Create virtual environment
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate

# Install dependencies
pip install -r requirements.txt

# Run the server
uvicorn main:app --reload --port 8000
\`\`\`

## API Documentation

Visit \`http://localhost:8000/docs\` for interactive API documentation.

## Endpoints

- \`GET /\` - API info
- \`GET /health\` - Health check
- \`GET /api/items\` - List all items
- \`POST /api/items\` - Create item
- \`GET /api/items/{id}\` - Get item by ID
- \`PUT /api/items/{id}\` - Update item
- \`DELETE /api/items/{id}\` - Delete item
`,
    language: 'markdown'
  });
  
  return {
    language: 'python',
    framework: 'FastAPI',
    files
  };
}

// Python Flask Backend Template
export function generatePythonFlaskBackend(projectName: string): BackendTemplate {
  const files: { path: string; content: string; language: string }[] = [];
  
  files.push({
    path: 'requirements.txt',
    content: `flask==3.0.0
flask-cors==4.0.0
python-dotenv==1.0.0
gunicorn==21.2.0`,
    language: 'text'
  });
  
  files.push({
    path: 'app.py',
    content: `"""${projectName} - Flask Backend"""
from flask import Flask, request, jsonify
from flask_cors import CORS
from datetime import datetime
import os
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)
CORS(app)

# In-memory storage
items = {}
item_counter = 0

@app.route('/')
def index():
    return jsonify({
        'message': 'Welcome to ${projectName} API',
        'version': '1.0.0'
    })

@app.route('/health')
def health():
    return jsonify({
        'status': 'healthy',
        'timestamp': datetime.now().isoformat()
    })

@app.route('/api/items', methods=['GET'])
def list_items():
    return jsonify(list(items.values()))

@app.route('/api/items', methods=['POST'])
def create_item():
    global item_counter
    data = request.json
    item_counter += 1
    item = {
        'id': item_counter,
        'name': data.get('name'),
        'description': data.get('description'),
        'created_at': datetime.now().isoformat()
    }
    items[item_counter] = item
    return jsonify(item), 201

@app.route('/api/items/<int:item_id>', methods=['GET'])
def get_item(item_id):
    if item_id not in items:
        return jsonify({'error': 'Item not found'}), 404
    return jsonify(items[item_id])

@app.route('/api/items/<int:item_id>', methods=['PUT'])
def update_item(item_id):
    if item_id not in items:
        return jsonify({'error': 'Item not found'}), 404
    data = request.json
    items[item_id].update({
        'name': data.get('name', items[item_id]['name']),
        'description': data.get('description', items[item_id]['description'])
    })
    return jsonify(items[item_id])

@app.route('/api/items/<int:item_id>', methods=['DELETE'])
def delete_item(item_id):
    if item_id not in items:
        return jsonify({'error': 'Item not found'}), 404
    del items[item_id]
    return jsonify({'message': 'Item deleted'})

if __name__ == '__main__':
    port = int(os.getenv('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)
`,
    language: 'python'
  });
  
  files.push({
    path: 'README.md',
    content: `# ${projectName}

Python Flask backend generated by AutoCoder.

## Getting Started

\`\`\`bash
pip install -r requirements.txt
python app.py
\`\`\`

Server runs on http://localhost:5000
`,
    language: 'markdown'
  });
  
  return {
    language: 'python',
    framework: 'Flask',
    files
  };
}

// Go Backend Template
export function generateGoBackend(projectName: string): BackendTemplate {
  const moduleName = projectName.toLowerCase().replace(/\s+/g, '-');
  const files: { path: string; content: string; language: string }[] = [];
  
  files.push({
    path: 'go.mod',
    content: `module ${moduleName}

go 1.21

require (
\tgithub.com/gin-gonic/gin v1.9.1
\tgithub.com/joho/godotenv v1.5.1
)`,
    language: 'text'
  });
  
  files.push({
    path: 'main.go',
    content: `package main

import (
\t"net/http"
\t"os"
\t"strconv"
\t"sync"
\t"time"

\t"github.com/gin-gonic/gin"
\t"github.com/joho/godotenv"
)

type Item struct {
\tID          int       \`json:"id"\`
\tName        string    \`json:"name"\`
\tDescription string    \`json:"description"\`
\tCreatedAt   time.Time \`json:"created_at"\`
}

type CreateItemRequest struct {
\tName        string \`json:"name" binding:"required"\`
\tDescription string \`json:"description"\`
}

var (
\titems   = make(map[int]Item)
\tcounter = 0
\tmu      sync.Mutex
)

func main() {
\tgodotenv.Load()
\t
\tr := gin.Default()
\t
\t// CORS middleware
\tr.Use(func(c *gin.Context) {
\t\tc.Header("Access-Control-Allow-Origin", "*")
\t\tc.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
\t\tc.Header("Access-Control-Allow-Headers", "Content-Type, Authorization")
\t\tif c.Request.Method == "OPTIONS" {
\t\t\tc.AbortWithStatus(204)
\t\t\treturn
\t\t}
\t\tc.Next()
\t})
\t
\t// Routes
\tr.GET("/", func(c *gin.Context) {
\t\tc.JSON(http.StatusOK, gin.H{
\t\t\t"message": "Welcome to ${projectName} API",
\t\t\t"version": "1.0.0",
\t\t})
\t})
\t
\tr.GET("/health", func(c *gin.Context) {
\t\tc.JSON(http.StatusOK, gin.H{
\t\t\t"status":    "healthy",
\t\t\t"timestamp": time.Now().Format(time.RFC3339),
\t\t})
\t})
\t
\tapi := r.Group("/api")
\t{
\t\tapi.GET("/items", listItems)
\t\tapi.POST("/items", createItem)
\t\tapi.GET("/items/:id", getItem)
\t\tapi.PUT("/items/:id", updateItem)
\t\tapi.DELETE("/items/:id", deleteItem)
\t}
\t
\tport := os.Getenv("PORT")
\tif port == "" {
\t\tport = "8080"
\t}
\t
\tr.Run(":" + port)
}

func listItems(c *gin.Context) {
\tmu.Lock()
\tdefer mu.Unlock()
\t
\tresult := make([]Item, 0, len(items))
\tfor _, item := range items {
\t\tresult = append(result, item)
\t}
\tc.JSON(http.StatusOK, result)
}

func createItem(c *gin.Context) {
\tvar req CreateItemRequest
\tif err := c.ShouldBindJSON(&req); err != nil {
\t\tc.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
\t\treturn
\t}
\t
\tmu.Lock()
\tdefer mu.Unlock()
\t
\tcounter++
\titem := Item{
\t\tID:          counter,
\t\tName:        req.Name,
\t\tDescription: req.Description,
\t\tCreatedAt:   time.Now(),
\t}
\titems[counter] = item
\t
\tc.JSON(http.StatusCreated, item)
}

func getItem(c *gin.Context) {
\tid, err := strconv.Atoi(c.Param("id"))
\tif err != nil {
\t\tc.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID"})
\t\treturn
\t}
\t
\tmu.Lock()
\tdefer mu.Unlock()
\t
\titem, exists := items[id]
\tif !exists {
\t\tc.JSON(http.StatusNotFound, gin.H{"error": "Item not found"})
\t\treturn
\t}
\t
\tc.JSON(http.StatusOK, item)
}

func updateItem(c *gin.Context) {
\tid, err := strconv.Atoi(c.Param("id"))
\tif err != nil {
\t\tc.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID"})
\t\treturn
\t}
\t
\tvar req CreateItemRequest
\tif err := c.ShouldBindJSON(&req); err != nil {
\t\tc.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
\t\treturn
\t}
\t
\tmu.Lock()
\tdefer mu.Unlock()
\t
\titem, exists := items[id]
\tif !exists {
\t\tc.JSON(http.StatusNotFound, gin.H{"error": "Item not found"})
\t\treturn
\t}
\t
\titem.Name = req.Name
\titem.Description = req.Description
\titems[id] = item
\t
\tc.JSON(http.StatusOK, item)
}

func deleteItem(c *gin.Context) {
\tid, err := strconv.Atoi(c.Param("id"))
\tif err != nil {
\t\tc.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID"})
\t\treturn
\t}
\t
\tmu.Lock()
\tdefer mu.Unlock()
\t
\tif _, exists := items[id]; !exists {
\t\tc.JSON(http.StatusNotFound, gin.H{"error": "Item not found"})
\t\treturn
\t}
\t
\tdelete(items, id)
\tc.JSON(http.StatusOK, gin.H{"message": "Item deleted"})
}
`,
    language: 'go'
  });
  
  files.push({
    path: 'Dockerfile',
    content: `FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
`,
    language: 'dockerfile'
  });
  
  files.push({
    path: 'README.md',
    content: `# ${projectName}

Go backend with Gin framework generated by AutoCoder.

## Getting Started

\`\`\`bash
# Download dependencies
go mod download

# Run the server
go run main.go
\`\`\`

Server runs on http://localhost:8080
`,
    language: 'markdown'
  });
  
  return {
    language: 'go',
    framework: 'Gin',
    files
  };
}

// Rust Backend Template (Actix-web)
export function generateRustBackend(projectName: string): BackendTemplate {
  const crateName = projectName.toLowerCase().replace(/\s+/g, '_');
  const files: { path: string; content: string; language: string }[] = [];
  
  files.push({
    path: 'Cargo.toml',
    content: `[package]
name = "${crateName}"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.10"
log = "0.4"
`,
    language: 'toml'
  });
  
  files.push({
    path: 'src/main.rs',
    content: `use actix_cors::Cors;
use actix_web::{web, App, HttpResponse, HttpServer, Responder};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Mutex;

#[derive(Debug, Clone, Serialize, Deserialize)]
struct Item {
    id: u32,
    name: String,
    description: Option<String>,
    created_at: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
struct CreateItem {
    name: String,
    description: Option<String>,
}

struct AppState {
    items: Mutex<HashMap<u32, Item>>,
    counter: Mutex<u32>,
}

async fn index() -> impl Responder {
    HttpResponse::Ok().json(serde_json::json!({
        "message": "Welcome to ${projectName} API",
        "version": "1.0.0"
    }))
}

async fn health() -> impl Responder {
    HttpResponse::Ok().json(serde_json::json!({
        "status": "healthy",
        "timestamp": Utc::now().to_rfc3339()
    }))
}

async fn list_items(data: web::Data<AppState>) -> impl Responder {
    let items = data.items.lock().unwrap();
    let result: Vec<Item> = items.values().cloned().collect();
    HttpResponse::Ok().json(result)
}

async fn create_item(
    data: web::Data<AppState>,
    body: web::Json<CreateItem>,
) -> impl Responder {
    let mut counter = data.counter.lock().unwrap();
    let mut items = data.items.lock().unwrap();
    
    *counter += 1;
    let item = Item {
        id: *counter,
        name: body.name.clone(),
        description: body.description.clone(),
        created_at: Utc::now(),
    };
    
    items.insert(*counter, item.clone());
    HttpResponse::Created().json(item)
}

async fn get_item(
    data: web::Data<AppState>,
    path: web::Path<u32>,
) -> impl Responder {
    let items = data.items.lock().unwrap();
    let id = path.into_inner();
    
    match items.get(&id) {
        Some(item) => HttpResponse::Ok().json(item),
        None => HttpResponse::NotFound().json(serde_json::json!({"error": "Item not found"})),
    }
}

async fn update_item(
    data: web::Data<AppState>,
    path: web::Path<u32>,
    body: web::Json<CreateItem>,
) -> impl Responder {
    let mut items = data.items.lock().unwrap();
    let id = path.into_inner();
    
    match items.get_mut(&id) {
        Some(item) => {
            item.name = body.name.clone();
            item.description = body.description.clone();
            HttpResponse::Ok().json(item.clone())
        }
        None => HttpResponse::NotFound().json(serde_json::json!({"error": "Item not found"})),
    }
}

async fn delete_item(
    data: web::Data<AppState>,
    path: web::Path<u32>,
) -> impl Responder {
    let mut items = data.items.lock().unwrap();
    let id = path.into_inner();
    
    match items.remove(&id) {
        Some(_) => HttpResponse::Ok().json(serde_json::json!({"message": "Item deleted"})),
        None => HttpResponse::NotFound().json(serde_json::json!({"error": "Item not found"})),
    }
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    dotenv::dotenv().ok();
    env_logger::init();
    
    let app_state = web::Data::new(AppState {
        items: Mutex::new(HashMap::new()),
        counter: Mutex::new(0),
    });
    
    let port = std::env::var("PORT").unwrap_or_else(|_| "8080".to_string());
    
    log::info!("Starting server on port {}", port);
    
    HttpServer::new(move || {
        let cors = Cors::permissive();
        
        App::new()
            .wrap(cors)
            .app_data(app_state.clone())
            .route("/", web::get().to(index))
            .route("/health", web::get().to(health))
            .service(
                web::scope("/api")
                    .route("/items", web::get().to(list_items))
                    .route("/items", web::post().to(create_item))
                    .route("/items/{id}", web::get().to(get_item))
                    .route("/items/{id}", web::put().to(update_item))
                    .route("/items/{id}", web::delete().to(delete_item))
            )
    })
    .bind(format!("0.0.0.0:{}", port))?
    .run()
    .await
}
`,
    language: 'rust'
  });
  
  files.push({
    path: 'README.md',
    content: `# ${projectName}

Rust backend with Actix-web framework generated by AutoCoder.

## Getting Started

\`\`\`bash
# Build and run
cargo run

# Build for production
cargo build --release
\`\`\`

Server runs on http://localhost:8080
`,
    language: 'markdown'
  });
  
  return {
    language: 'rust',
    framework: 'Actix-web',
    files
  };
}

// Get available backend languages
export function getAvailableBackends(): { language: string; frameworks: string[] }[] {
  return [
    { language: 'Node.js', frameworks: ['Express', 'Fastify', 'Koa', 'Hono'] },
    { language: 'Python', frameworks: ['FastAPI', 'Flask', 'Django'] },
    { language: 'Go', frameworks: ['Gin', 'Echo', 'Fiber'] },
    { language: 'Rust', frameworks: ['Actix-web', 'Axum', 'Rocket'] }
  ];
}

// Generate backend by language and framework
export function generateBackend(
  projectName: string,
  language: string,
  framework?: string
): BackendTemplate | null {
  const lang = language.toLowerCase();
  
  if (lang === 'python') {
    if (framework?.toLowerCase() === 'flask') {
      return generatePythonFlaskBackend(projectName);
    }
    return generatePythonFastAPIBackend(projectName);
  }
  
  if (lang === 'go' || lang === 'golang') {
    return generateGoBackend(projectName);
  }
  
  if (lang === 'rust') {
    return generateRustBackend(projectName);
  }
  
  return null;
}
