export interface ArchitecturePattern {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  suitableFor: string[];
  complexity: 'simple' | 'medium' | 'complex';
  folderStructure: Record<string, string[]>;
  layers: { name: string; responsibility: string; technologies: string[] }[];
  dataFlow: string[];
  stateManagement: string;
  authentication: string;
  errorHandling: string;
  scalability: string;
  deploymentModel: string;
  pros: string[];
  cons: string[];
}

export const architecturePatterns: ArchitecturePattern[] = [
  {
    id: 'monolith',
    name: 'Monolith',
    description: 'A single deployable unit containing all application logic, UI, business rules, and data access in one codebase. Ideal for small teams and MVPs where speed of development matters more than scalability.',
    keywords: ['monolith', 'single-app', 'mvp', 'startup', 'simple', 'all-in-one', 'rapid-development'],
    suitableFor: ['MVPs and prototypes', 'Small teams with 1-5 developers', 'Applications with limited scope', 'Projects with tight deadlines', 'Internal tools and admin panels'],
    complexity: 'simple',
    folderStructure: {
      'src/': ['app.ts', 'config.ts', 'server.ts'],
      'src/routes/': ['auth.ts', 'users.ts', 'products.ts', 'orders.ts'],
      'src/models/': ['user.ts', 'product.ts', 'order.ts'],
      'src/views/': ['layout.html', 'home.html', 'dashboard.html'],
      'src/middleware/': ['auth.ts', 'validation.ts', 'error-handler.ts'],
      'src/utils/': ['logger.ts', 'helpers.ts', 'constants.ts'],
      'src/services/': ['email.ts', 'payment.ts', 'notification.ts'],
      'public/': ['styles.css', 'app.js', 'favicon.ico'],
    },
    layers: [
      { name: 'Presentation', responsibility: 'Handle HTTP requests, render views, manage user input', technologies: ['Express', 'EJS', 'Handlebars'] },
      { name: 'Business Logic', responsibility: 'Core application rules, validation, and processing', technologies: ['Node.js', 'TypeScript'] },
      { name: 'Data Access', responsibility: 'Database queries, ORM operations, data persistence', technologies: ['Drizzle', 'PostgreSQL', 'Redis'] },
    ],
    dataFlow: ['Client sends HTTP request', 'Router matches handler', 'Middleware processes request', 'Controller calls service', 'Service executes business logic', 'Data layer queries database', 'Response rendered and returned'],
    stateManagement: 'Server-side sessions stored in database or Redis with cookie-based session IDs',
    authentication: 'Session-based authentication with bcrypt password hashing and CSRF protection',
    errorHandling: 'Global error middleware catches unhandled exceptions and returns appropriate HTTP status codes with error messages',
    scalability: 'Vertical scaling by adding more resources to the single server; horizontal scaling requires sticky sessions or shared session store',
    deploymentModel: 'Single deployment artifact deployed to one or more servers behind a load balancer',
    pros: ['Simple to develop and debug', 'Easy to test end-to-end', 'Single deployment unit simplifies DevOps', 'Low operational overhead', 'Straightforward local development'],
    cons: ['Difficult to scale individual components independently', 'Entire application must be redeployed for any change', 'Technology lock-in across the entire stack', 'Growing codebase becomes harder to maintain'],
  },
  {
    id: 'modular-monolith',
    name: 'Modular Monolith',
    description: 'A monolithic application structured into well-defined modules with clear boundaries and interfaces. Each module encapsulates a specific business domain while sharing the same deployment unit.',
    keywords: ['modular', 'monolith', 'domain-driven', 'bounded-context', 'organized', 'maintainable'],
    suitableFor: ['Medium-sized teams', 'Applications that may evolve to microservices', 'Domain-driven design projects', 'Teams wanting monolith simplicity with better organization'],
    complexity: 'medium',
    folderStructure: {
      'src/modules/users/': ['controller.ts', 'service.ts', 'repository.ts', 'types.ts', 'routes.ts'],
      'src/modules/orders/': ['controller.ts', 'service.ts', 'repository.ts', 'types.ts', 'routes.ts'],
      'src/modules/products/': ['controller.ts', 'service.ts', 'repository.ts', 'types.ts', 'routes.ts'],
      'src/modules/payments/': ['controller.ts', 'service.ts', 'repository.ts', 'types.ts', 'routes.ts'],
      'src/shared/': ['database.ts', 'logger.ts', 'events.ts', 'types.ts'],
      'src/infrastructure/': ['http-server.ts', 'middleware.ts', 'config.ts'],
      'src/': ['app.ts', 'bootstrap.ts'],
    },
    layers: [
      { name: 'API Layer', responsibility: 'Route definitions and request/response handling per module', technologies: ['Express', 'Fastify'] },
      { name: 'Module Layer', responsibility: 'Encapsulated business logic with clear interfaces between modules', technologies: ['TypeScript', 'Node.js'] },
      { name: 'Repository Layer', responsibility: 'Data access abstracted behind repository interfaces per module', technologies: ['Drizzle', 'TypeORM', 'PostgreSQL'] },
      { name: 'Infrastructure Layer', responsibility: 'Cross-cutting concerns like logging, configuration, and messaging', technologies: ['Winston', 'dotenv', 'EventEmitter'] },
    ],
    dataFlow: ['Request enters through HTTP server', 'Router delegates to module controller', 'Controller validates input', 'Service layer processes business logic', 'Cross-module communication via internal events', 'Repository persists data', 'Response returned through controller'],
    stateManagement: 'Each module manages its own state; cross-module communication via events or direct service calls through defined interfaces',
    authentication: 'Shared authentication module providing middleware that other modules consume',
    errorHandling: 'Each module defines its own error types; global error handler maps module errors to HTTP responses',
    scalability: 'Vertical scaling with potential to extract modules into separate services when needed',
    deploymentModel: 'Single deployment unit with module boundaries making future extraction to microservices straightforward',
    pros: ['Clear separation of concerns within monolith', 'Easier to evolve into microservices later', 'Better code organization and team ownership', 'Simpler than microservices while maintaining modularity'],
    cons: ['Requires discipline to maintain module boundaries', 'Shared database can create coupling', 'Still limited to single deployment unit', 'Module interface design requires upfront planning'],
  },
  {
    id: 'microservices',
    name: 'Microservices',
    description: 'Application decomposed into small, independently deployable services, each owning its own data and communicating via APIs or messaging. Each service focuses on a single business capability.',
    keywords: ['microservices', 'distributed', 'independent', 'scalable', 'containerized', 'api-gateway'],
    suitableFor: ['Large teams with multiple squads', 'High-traffic applications requiring independent scaling', 'Organizations needing polyglot technology stacks', 'Systems requiring high availability and fault isolation'],
    complexity: 'complex',
    folderStructure: {
      'services/user-service/src/': ['app.ts', 'routes.ts', 'service.ts', 'repository.ts', 'types.ts'],
      'services/order-service/src/': ['app.ts', 'routes.ts', 'service.ts', 'repository.ts', 'types.ts'],
      'services/payment-service/src/': ['app.ts', 'routes.ts', 'service.ts', 'repository.ts', 'types.ts'],
      'services/notification-service/src/': ['app.ts', 'routes.ts', 'service.ts', 'types.ts'],
      'api-gateway/': ['gateway.ts', 'routes.ts', 'auth-middleware.ts', 'rate-limiter.ts'],
      'shared/': ['proto-definitions/', 'event-schemas/', 'common-types/'],
      'infrastructure/': ['docker-compose.yml', 'k8s/', 'terraform/'],
      'libs/common/': ['logger.ts', 'tracing.ts', 'health-check.ts'],
    },
    layers: [
      { name: 'API Gateway', responsibility: 'Route requests to appropriate services, handle cross-cutting concerns', technologies: ['Kong', 'Express Gateway', 'Nginx'] },
      { name: 'Service Layer', responsibility: 'Individual microservices implementing specific business capabilities', technologies: ['Express', 'Fastify', 'NestJS'] },
      { name: 'Data Layer', responsibility: 'Each service owns its own database for data autonomy', technologies: ['PostgreSQL', 'MongoDB', 'Redis'] },
      { name: 'Messaging Layer', responsibility: 'Asynchronous communication between services', technologies: ['RabbitMQ', 'Kafka', 'NATS'] },
      { name: 'Infrastructure Layer', responsibility: 'Service discovery, orchestration, monitoring', technologies: ['Kubernetes', 'Docker', 'Prometheus'] },
    ],
    dataFlow: ['Client sends request to API Gateway', 'Gateway authenticates and routes request', 'Target service processes request', 'Service queries its own database', 'Service publishes events for side effects', 'Other services consume events asynchronously', 'Response returned through gateway', 'Saga orchestrator manages distributed transactions'],
    stateManagement: 'Each service manages its own state independently; distributed state coordinated through event sourcing or saga patterns',
    authentication: 'JWT-based authentication at API gateway with token validation propagated to individual services',
    errorHandling: 'Circuit breaker pattern prevents cascade failures; each service implements retry logic with exponential backoff; centralized error tracking',
    scalability: 'Independent horizontal scaling per service based on load; auto-scaling with container orchestration',
    deploymentModel: 'Independent deployment per service using containers orchestrated by Kubernetes with blue-green or canary deployment strategies',
    pros: ['Independent scaling and deployment per service', 'Technology diversity across services', 'Fault isolation prevents cascade failures', 'Teams can work independently on different services'],
    cons: ['Significant operational complexity', 'Distributed tracing and debugging is challenging', 'Network latency and data consistency challenges', 'Requires mature DevOps practices and tooling'],
  },
  {
    id: 'serverless',
    name: 'Serverless',
    description: 'Application logic deployed as individual functions triggered by events, with infrastructure fully managed by cloud providers. Functions scale automatically and billing is per-invocation.',
    keywords: ['serverless', 'lambda', 'functions', 'faas', 'cloud-native', 'event-triggered', 'pay-per-use'],
    suitableFor: ['Event-driven workloads', 'Variable or unpredictable traffic patterns', 'Rapid prototyping and experimentation', 'Cost-sensitive applications with sporadic usage'],
    complexity: 'medium',
    folderStructure: {
      'functions/': ['create-user.ts', 'process-order.ts', 'send-notification.ts', 'generate-report.ts'],
      'functions/triggers/': ['http-trigger.ts', 'queue-trigger.ts', 'schedule-trigger.ts', 'storage-trigger.ts'],
      'layers/': ['common-deps/', 'auth-layer/', 'db-layer/'],
      'api/': ['openapi.yaml', 'routes.ts'],
      'infrastructure/': ['serverless.yml', 'cloudformation.json', 'iam-policies.json'],
      'shared/': ['types.ts', 'validators.ts', 'utils.ts'],
    },
    layers: [
      { name: 'API Layer', responsibility: 'API Gateway routes and request transformation', technologies: ['AWS API Gateway', 'Azure API Management', 'Cloudflare Workers'] },
      { name: 'Function Layer', responsibility: 'Individual function handlers implementing business logic', technologies: ['AWS Lambda', 'Azure Functions', 'Google Cloud Functions'] },
      { name: 'Integration Layer', responsibility: 'Connections to managed services and external APIs', technologies: ['DynamoDB', 'S3', 'SQS', 'EventBridge'] },
    ],
    dataFlow: ['Event triggers function execution', 'API Gateway validates request', 'Function cold starts or warm invocation', 'Business logic processes event', 'Function interacts with managed services', 'Results stored or forwarded to next function', 'Response returned to caller'],
    stateManagement: 'Stateless functions with state persisted in external stores like DynamoDB or Redis; step functions for workflow state',
    authentication: 'API Gateway authorizers with JWT validation or Lambda authorizers for custom authentication logic',
    errorHandling: 'Dead letter queues capture failed invocations; retry policies configured per trigger type; CloudWatch alarms for error rate monitoring',
    scalability: 'Automatic scaling from zero to thousands of concurrent invocations managed entirely by the cloud provider',
    deploymentModel: 'Infrastructure as code with Serverless Framework or AWS SAM; individual function deployments with versioning and aliases',
    pros: ['Zero server management and automatic scaling', 'Pay only for actual compute time used', 'Rapid development and deployment cycles', 'Built-in high availability'],
    cons: ['Cold start latency can impact user experience', 'Vendor lock-in to specific cloud provider', 'Limited execution time and memory constraints', 'Complex local development and testing'],
  },
  {
    id: 'event-driven',
    name: 'Event-Driven Architecture',
    description: 'System components communicate through events, enabling loose coupling and asynchronous processing. Producers emit events without knowledge of consumers, allowing flexible system composition.',
    keywords: ['event-driven', 'async', 'pub-sub', 'message-queue', 'reactive', 'decoupled', 'streaming'],
    suitableFor: ['Real-time data processing systems', 'Systems requiring loose coupling between components', 'Applications with complex workflows', 'High-throughput data pipelines'],
    complexity: 'complex',
    folderStructure: {
      'src/producers/': ['order-producer.ts', 'user-producer.ts', 'payment-producer.ts'],
      'src/consumers/': ['email-consumer.ts', 'analytics-consumer.ts', 'inventory-consumer.ts'],
      'src/events/': ['event-types.ts', 'event-store.ts', 'event-bus.ts', 'serializers.ts'],
      'src/handlers/': ['order-handler.ts', 'payment-handler.ts', 'notification-handler.ts'],
      'src/projections/': ['order-view.ts', 'dashboard-view.ts', 'report-view.ts'],
      'src/infrastructure/': ['broker-config.ts', 'dead-letter.ts', 'retry-policy.ts'],
      'src/api/': ['rest-endpoints.ts', 'websocket-server.ts'],
    },
    layers: [
      { name: 'Event Producers', responsibility: 'Generate and publish domain events to the message broker', technologies: ['Kafka Producer', 'RabbitMQ Publisher', 'EventEmitter'] },
      { name: 'Event Bus', responsibility: 'Route events from producers to consumers with guaranteed delivery', technologies: ['Apache Kafka', 'RabbitMQ', 'AWS EventBridge', 'Redis Streams'] },
      { name: 'Event Consumers', responsibility: 'Subscribe to events and execute corresponding business logic', technologies: ['Kafka Consumer', 'RabbitMQ Subscriber', 'SQS'] },
      { name: 'Event Store', responsibility: 'Persist all events for replay, audit, and rebuilding state', technologies: ['EventStoreDB', 'PostgreSQL', 'DynamoDB'] },
      { name: 'Projection Layer', responsibility: 'Build read-optimized views from event streams', technologies: ['PostgreSQL Views', 'Elasticsearch', 'Redis'] },
    ],
    dataFlow: ['Action triggers event creation in producer', 'Event serialized and published to message broker', 'Broker routes event to registered consumers', 'Consumers process event independently', 'Event stored in event log for replay', 'Projections updated from event stream', 'Read models serve query requests', 'Failed events sent to dead letter queue'],
    stateManagement: 'Event sourcing where state is derived by replaying events from the event store; CQRS separates read and write models',
    authentication: 'Service-to-service authentication via mutual TLS or API keys; user authentication at the API gateway level',
    errorHandling: 'Dead letter queues for unprocessable events; idempotent consumers prevent duplicate processing; circuit breakers on external integrations',
    scalability: 'Horizontal scaling of consumers independently; partition-based parallelism in message brokers; backpressure mechanisms prevent overload',
    deploymentModel: 'Independent deployment of producers and consumers; message broker deployed as managed service or clustered infrastructure',
    pros: ['Loose coupling between system components', 'Natural support for async processing and eventual consistency', 'Easy to add new consumers without modifying producers', 'Built-in audit trail through event log'],
    cons: ['Eventual consistency can be complex to manage', 'Event ordering and idempotency require careful design', 'Debugging distributed event flows is challenging', 'Event schema evolution requires versioning strategy'],
  },
  {
    id: 'cqrs',
    name: 'CQRS (Command Query Responsibility Segregation)',
    description: 'Separates read and write operations into distinct models, allowing each to be optimized independently. Commands modify state while queries retrieve data from optimized read models.',
    keywords: ['cqrs', 'command-query', 'read-write-split', 'event-sourcing', 'domain-driven', 'performance'],
    suitableFor: ['Applications with asymmetric read/write loads', 'Complex domains requiring different read and write models', 'Systems needing audit trails and temporal queries', 'High-performance applications with heavy read loads'],
    complexity: 'complex',
    folderStructure: {
      'src/commands/': ['create-order.ts', 'update-user.ts', 'process-payment.ts', 'command-bus.ts'],
      'src/queries/': ['get-orders.ts', 'get-user-profile.ts', 'search-products.ts', 'query-bus.ts'],
      'src/domain/': ['order-aggregate.ts', 'user-aggregate.ts', 'domain-events.ts'],
      'src/read-models/': ['order-read-model.ts', 'user-dashboard.ts', 'product-catalog.ts'],
      'src/projections/': ['order-projector.ts', 'analytics-projector.ts'],
      'src/infrastructure/': ['write-db.ts', 'read-db.ts', 'event-store.ts', 'message-bus.ts'],
    },
    layers: [
      { name: 'Command Side', responsibility: 'Handle write operations through domain aggregates and enforce business rules', technologies: ['TypeScript', 'Domain Aggregates', 'Event Store'] },
      { name: 'Query Side', responsibility: 'Serve optimized read models for fast data retrieval', technologies: ['Elasticsearch', 'Redis', 'PostgreSQL Views'] },
      { name: 'Event Processing', responsibility: 'Synchronize write and read models through domain events', technologies: ['Kafka', 'RabbitMQ', 'In-memory Bus'] },
      { name: 'API Layer', responsibility: 'Expose separate endpoints for commands and queries', technologies: ['Express', 'GraphQL', 'REST'] },
    ],
    dataFlow: ['Client sends command through API', 'Command handler validates and processes command', 'Domain aggregate applies business rules', 'Domain events emitted from aggregate', 'Event store persists events', 'Projectors consume events and update read models', 'Query handler reads from optimized read model', 'Response returned to client'],
    stateManagement: 'Write side uses event sourcing with aggregates; read side maintains denormalized projections optimized for specific queries',
    authentication: 'Command endpoints require write permissions; query endpoints may have relaxed read-only access controls',
    errorHandling: 'Command validation errors returned synchronously; projection failures handled with retry queues; eventual consistency monitored with lag metrics',
    scalability: 'Read and write sides scale independently; read replicas for query load; write side optimized for consistency',
    deploymentModel: 'Can be deployed as single unit or separate read/write services; event store as dedicated infrastructure component',
    pros: ['Independent optimization of read and write paths', 'Natural fit for event sourcing and audit trails', 'Better performance through specialized read models', 'Clear separation of concerns'],
    cons: ['Increased complexity with two data models', 'Eventual consistency between read and write sides', 'More infrastructure to manage', 'Steeper learning curve for development teams'],
  },
  {
    id: 'hexagonal',
    name: 'Hexagonal Architecture (Ports and Adapters)',
    description: 'Application core is isolated from external concerns through ports (interfaces) and adapters (implementations). The core defines what it needs; adapters provide concrete implementations.',
    keywords: ['hexagonal', 'ports-adapters', 'clean', 'testable', 'framework-agnostic', 'dependency-inversion'],
    suitableFor: ['Applications requiring high testability', 'Projects that may switch frameworks or databases', 'Domain-heavy applications with complex business rules', 'Long-lived projects requiring maintainability'],
    complexity: 'medium',
    folderStructure: {
      'src/core/domain/': ['order.ts', 'user.ts', 'product.ts', 'value-objects.ts'],
      'src/core/ports/in/': ['create-order.port.ts', 'get-user.port.ts', 'process-payment.port.ts'],
      'src/core/ports/out/': ['order-repository.port.ts', 'payment-gateway.port.ts', 'email-sender.port.ts'],
      'src/core/services/': ['order-service.ts', 'user-service.ts', 'payment-service.ts'],
      'src/adapters/in/http/': ['order-controller.ts', 'user-controller.ts', 'routes.ts'],
      'src/adapters/in/cli/': ['import-command.ts', 'report-command.ts'],
      'src/adapters/out/persistence/': ['postgres-order-repo.ts', 'postgres-user-repo.ts'],
      'src/adapters/out/external/': ['stripe-payment.ts', 'sendgrid-email.ts'],
      'src/config/': ['app.ts', 'dependency-injection.ts', 'database.ts'],
    },
    layers: [
      { name: 'Domain Core', responsibility: 'Business entities, value objects, and domain logic with zero external dependencies', technologies: ['TypeScript', 'Pure domain classes'] },
      { name: 'Application Services', responsibility: 'Use cases orchestrating domain objects through port interfaces', technologies: ['TypeScript', 'Dependency Injection'] },
      { name: 'Inbound Adapters', responsibility: 'Translate external requests into application service calls', technologies: ['Express', 'GraphQL', 'CLI'] },
      { name: 'Outbound Adapters', responsibility: 'Implement port interfaces for external systems', technologies: ['PostgreSQL', 'Stripe SDK', 'SendGrid'] },
    ],
    dataFlow: ['External request enters through inbound adapter', 'Adapter translates to application service call', 'Service orchestrates domain objects', 'Domain logic executes business rules', 'Service calls outbound ports for side effects', 'Outbound adapters interact with external systems', 'Result flows back through adapter to caller'],
    stateManagement: 'Domain state managed through aggregate roots; application state flows through service layer; no framework-specific state management in core',
    authentication: 'Authentication adapter implements a security port; core defines authorization rules through domain policies',
    errorHandling: 'Domain exceptions for business rule violations; adapter exceptions for infrastructure failures; application service maps between exception types',
    scalability: 'Core logic is framework-agnostic enabling migration to any runtime; adapters can be swapped for higher-performance alternatives',
    deploymentModel: 'Typically deployed as single unit; core can be packaged as library for reuse across different deployment targets',
    pros: ['Highly testable with mock adapters', 'Framework and database agnostic core', 'Clear dependency direction from outside inward', 'Easy to swap external dependencies'],
    cons: ['More boilerplate code with port/adapter interfaces', 'Can be over-engineered for simple applications', 'Requires discipline to maintain boundaries', 'Initial setup takes more time'],
  },
  {
    id: 'clean-architecture',
    name: 'Clean Architecture',
    description: 'Concentric layers with dependencies pointing inward. The innermost layer contains enterprise business rules, surrounded by application rules, interface adapters, and frameworks.',
    keywords: ['clean', 'uncle-bob', 'dependency-rule', 'enterprise', 'testable', 'independent', 'layers'],
    suitableFor: ['Enterprise applications with complex business rules', 'Projects requiring long-term maintainability', 'Teams practicing domain-driven design', 'Applications needing high test coverage'],
    complexity: 'complex',
    folderStructure: {
      'src/entities/': ['user.entity.ts', 'order.entity.ts', 'product.entity.ts', 'value-objects/'],
      'src/use-cases/': ['create-order.ts', 'register-user.ts', 'process-payment.ts', 'get-dashboard.ts'],
      'src/interfaces/controllers/': ['order-controller.ts', 'user-controller.ts', 'auth-controller.ts'],
      'src/interfaces/presenters/': ['order-presenter.ts', 'user-presenter.ts', 'error-presenter.ts'],
      'src/interfaces/gateways/': ['order-gateway.ts', 'user-gateway.ts', 'payment-gateway.ts'],
      'src/frameworks/web/': ['express-app.ts', 'routes.ts', 'middleware.ts'],
      'src/frameworks/database/': ['drizzle-config.ts', 'repositories.ts', 'migrations/'],
      'src/frameworks/external/': ['stripe-service.ts', 'email-service.ts', 'storage-service.ts'],
    },
    layers: [
      { name: 'Entities', responsibility: 'Enterprise-wide business rules and domain objects independent of any application', technologies: ['TypeScript', 'Domain primitives'] },
      { name: 'Use Cases', responsibility: 'Application-specific business rules orchestrating entities', technologies: ['TypeScript', 'Dependency Injection'] },
      { name: 'Interface Adapters', responsibility: 'Convert data between use case format and external format', technologies: ['Controllers', 'Presenters', 'Gateways'] },
      { name: 'Frameworks & Drivers', responsibility: 'External tools, frameworks, and delivery mechanisms', technologies: ['Express', 'PostgreSQL', 'React', 'Stripe'] },
    ],
    dataFlow: ['Request enters through framework layer', 'Controller converts request to use case input', 'Use case orchestrates entities and business rules', 'Entities enforce invariants and domain logic', 'Use case calls gateway interfaces for persistence', 'Gateway implementation executes database operations', 'Presenter formats use case output', 'Framework delivers response to client'],
    stateManagement: 'Entities maintain their own invariants; use cases manage application workflow state; no framework-specific state in inner layers',
    authentication: 'Authentication use case in application layer; authorization policies in entity layer; token management in framework layer',
    errorHandling: 'Domain errors in entity layer; application errors in use case layer; HTTP errors mapped in controller layer; global error handler in framework layer',
    scalability: 'Inner layers remain stable as framework layers change; enables parallel development across layers; technology migrations confined to outer layers',
    deploymentModel: 'Flexible deployment from monolith to microservices; inner layers packaged as reusable libraries',
    pros: ['Independence from frameworks and external agencies', 'Highly testable at every layer', 'Clear dependency rule prevents architectural erosion', 'Business rules isolated from delivery mechanism'],
    cons: ['Significant boilerplate and indirection', 'Steep learning curve for teams new to the pattern', 'Can feel over-engineered for simple CRUD applications', 'Requires ongoing discipline to maintain layer boundaries'],
  },
  {
    id: 'mvc',
    name: 'MVC (Model-View-Controller)',
    description: 'Classic architectural pattern separating application into three interconnected components: Models for data and business logic, Views for presentation, and Controllers for input handling.',
    keywords: ['mvc', 'model-view-controller', 'traditional', 'web-framework', 'separation-of-concerns', 'server-rendered'],
    suitableFor: ['Traditional web applications', 'Server-rendered applications', 'CRUD-heavy applications', 'Teams familiar with Rails/Django/Laravel patterns'],
    complexity: 'simple',
    folderStructure: {
      'src/models/': ['user.ts', 'post.ts', 'comment.ts', 'category.ts'],
      'src/views/': ['users/', 'posts/', 'layouts/', 'partials/'],
      'src/controllers/': ['user-controller.ts', 'post-controller.ts', 'auth-controller.ts', 'admin-controller.ts'],
      'src/routes/': ['web.ts', 'api.ts', 'admin.ts'],
      'src/middleware/': ['auth.ts', 'csrf.ts', 'rate-limit.ts'],
      'public/': ['css/', 'js/', 'images/'],
    },
    layers: [
      { name: 'Model', responsibility: 'Data representation, business logic, and database interaction', technologies: ['Drizzle', 'Sequelize', 'Mongoose'] },
      { name: 'View', responsibility: 'Render user interface and display data from models', technologies: ['EJS', 'Pug', 'Handlebars', 'React'] },
      { name: 'Controller', responsibility: 'Handle user input, coordinate model and view interaction', technologies: ['Express', 'Koa', 'Fastify'] },
    ],
    dataFlow: ['User interacts with View', 'Controller receives user input', 'Controller updates Model with new data', 'Model validates and persists changes', 'Model notifies Controller of state change', 'Controller selects appropriate View', 'View renders updated data to user'],
    stateManagement: 'Model holds application state; Controller manages request lifecycle; View is stateless and renders from model data',
    authentication: 'Controller-based authentication middleware validates credentials; session state maintained in model layer',
    errorHandling: 'Controllers catch model exceptions and render appropriate error views; validation errors displayed inline in forms',
    scalability: 'Horizontal scaling with load balancer and shared session store; database read replicas for read-heavy workloads',
    deploymentModel: 'Single application server deployment with static assets served through CDN',
    pros: ['Well-understood pattern with extensive documentation', 'Clear separation between data, logic, and presentation', 'Easy to find developers with MVC experience', 'Frameworks provide strong conventions'],
    cons: ['Controllers can become bloated with business logic', 'Tight coupling between views and models in some implementations', 'Not ideal for complex single-page applications', 'View logic can leak into controllers'],
  },
  {
    id: 'mvvm',
    name: 'MVVM (Model-View-ViewModel)',
    description: 'Architectural pattern where the ViewModel acts as an intermediary between Model and View, providing data binding and command handling. Popular in modern frontend frameworks.',
    keywords: ['mvvm', 'model-view-viewmodel', 'data-binding', 'reactive', 'frontend', 'spa', 'two-way-binding'],
    suitableFor: ['Rich client-side applications', 'Single-page applications with complex UI state', 'Applications requiring two-way data binding', 'Desktop and mobile applications'],
    complexity: 'medium',
    folderStructure: {
      'src/models/': ['user.model.ts', 'product.model.ts', 'order.model.ts', 'api-service.ts'],
      'src/viewmodels/': ['user-list.vm.ts', 'product-detail.vm.ts', 'checkout.vm.ts', 'dashboard.vm.ts'],
      'src/views/': ['UserList.tsx', 'ProductDetail.tsx', 'Checkout.tsx', 'Dashboard.tsx'],
      'src/services/': ['api.ts', 'auth.ts', 'storage.ts', 'navigation.ts'],
      'src/stores/': ['root-store.ts', 'user-store.ts', 'cart-store.ts'],
      'src/utils/': ['formatters.ts', 'validators.ts', 'helpers.ts'],
    },
    layers: [
      { name: 'Model', responsibility: 'Data structures, API communication, and business rules', technologies: ['TypeScript', 'Axios', 'Fetch API'] },
      { name: 'ViewModel', responsibility: 'Presentation logic, data transformation, and command handling', technologies: ['MobX', 'Vue Composition API', 'Observable patterns'] },
      { name: 'View', responsibility: 'Declarative UI templates bound to ViewModel properties', technologies: ['React', 'Vue', 'Angular', 'Svelte'] },
    ],
    dataFlow: ['User interacts with View', 'View triggers ViewModel command', 'ViewModel validates input', 'ViewModel calls Model for data operations', 'Model communicates with backend API', 'Model returns updated data', 'ViewModel transforms data for display', 'View automatically updates through data binding'],
    stateManagement: 'ViewModel maintains UI state with observable properties; Model manages domain state; two-way data binding synchronizes View and ViewModel',
    authentication: 'Auth service in model layer; ViewModel exposes auth state and commands; View reacts to authentication changes',
    errorHandling: 'ViewModel catches model errors and exposes error state properties; View renders error states declaratively based on ViewModel bindings',
    scalability: 'Client-side scaling through code splitting and lazy loading; backend scaling independent of frontend architecture',
    deploymentModel: 'Static frontend deployed to CDN; API backend deployed independently',
    pros: ['Clean separation of UI logic from business logic', 'Excellent testability of ViewModels without UI', 'Natural fit for reactive UI frameworks', 'Reduced boilerplate with data binding'],
    cons: ['Data binding can create performance issues with large datasets', 'ViewModel complexity grows with UI complexity', 'Debugging binding issues can be challenging', 'Memory management concerns with observable subscriptions'],
  },
  {
    id: 'layered',
    name: 'Layered Architecture',
    description: 'Traditional N-tier architecture where each layer has a specific responsibility and can only communicate with the layer directly below it. Provides clear organizational structure.',
    keywords: ['layered', 'n-tier', 'traditional', 'organized', 'horizontal', 'enterprise'],
    suitableFor: ['Enterprise applications with clear functional tiers', 'Teams transitioning from traditional architectures', 'Applications with well-defined responsibilities at each tier', 'Systems requiring strict access control between layers'],
    complexity: 'simple',
    folderStructure: {
      'src/presentation/': ['controllers/', 'views/', 'dto/', 'middleware/'],
      'src/business/': ['services/', 'validators/', 'rules/', 'workflows/'],
      'src/persistence/': ['repositories/', 'models/', 'migrations/', 'seeds/'],
      'src/infrastructure/': ['config/', 'logging/', 'caching/', 'messaging/'],
      'src/shared/': ['types.ts', 'constants.ts', 'exceptions.ts'],
    },
    layers: [
      { name: 'Presentation Layer', responsibility: 'Handle HTTP requests, render responses, manage user sessions', technologies: ['Express', 'React', 'Angular'] },
      { name: 'Business Logic Layer', responsibility: 'Implement business rules, validation, and workflow orchestration', technologies: ['TypeScript', 'Node.js'] },
      { name: 'Persistence Layer', responsibility: 'Data access, ORM operations, query optimization', technologies: ['Drizzle', 'PostgreSQL', 'Redis'] },
      { name: 'Infrastructure Layer', responsibility: 'Cross-cutting concerns like logging, caching, and external integrations', technologies: ['Winston', 'Redis', 'AWS SDK'] },
    ],
    dataFlow: ['Request enters presentation layer', 'Controller validates and transforms input', 'Business service applies rules and logic', 'Persistence layer executes database operations', 'Results propagate back up through layers', 'Presentation layer formats response'],
    stateManagement: 'Each layer manages its own state; session state in presentation layer; business state in service layer; persistent state in data layer',
    authentication: 'Presentation layer handles authentication middleware; business layer enforces authorization rules',
    errorHandling: 'Each layer defines its own exception types; errors propagate upward through layers; presentation layer maps exceptions to user-facing messages',
    scalability: 'Individual tiers can be scaled independently when deployed separately; caching at multiple layers reduces load',
    deploymentModel: 'Can be deployed as monolith or with separate tier deployments behind load balancers',
    pros: ['Simple and well-understood organizational pattern', 'Clear responsibility boundaries between layers', 'Easy onboarding for new developers', 'Testable with layer-specific unit tests'],
    cons: ['Can lead to unnecessary pass-through code', 'Changes often cascade through multiple layers', 'Performance overhead from layer-to-layer communication', 'Rigid structure can be constraining for complex domains'],
  },
  {
    id: 'plugin-based',
    name: 'Plugin-Based Architecture',
    description: 'Core system provides extension points where plugins add functionality. The core is minimal and stable, while plugins provide domain-specific features that can be added or removed independently.',
    keywords: ['plugin', 'extensible', 'modular', 'addon', 'extension', 'customizable', 'marketplace'],
    suitableFor: ['Applications requiring extensibility by third parties', 'CMS and platform products', 'Tools with diverse feature sets', 'Products with marketplace ecosystems'],
    complexity: 'medium',
    folderStructure: {
      'src/core/': ['kernel.ts', 'plugin-manager.ts', 'hook-system.ts', 'config.ts'],
      'src/core/interfaces/': ['plugin.interface.ts', 'hook.interface.ts', 'storage.interface.ts'],
      'src/plugins/auth/': ['index.ts', 'routes.ts', 'middleware.ts'],
      'src/plugins/analytics/': ['index.ts', 'tracker.ts', 'dashboard.ts'],
      'src/plugins/payments/': ['index.ts', 'processor.ts', 'webhooks.ts'],
      'src/plugins/notifications/': ['index.ts', 'channels.ts', 'templates.ts'],
      'src/api/': ['routes.ts', 'middleware.ts', 'server.ts'],
    },
    layers: [
      { name: 'Core Kernel', responsibility: 'Minimal core providing plugin lifecycle management and extension points', technologies: ['TypeScript', 'Node.js'] },
      { name: 'Plugin Interface', responsibility: 'Define contracts that plugins must implement for registration and execution', technologies: ['TypeScript Interfaces', 'Abstract Classes'] },
      { name: 'Plugin Layer', responsibility: 'Individual plugins implementing features through defined extension points', technologies: ['TypeScript', 'Various per plugin'] },
      { name: 'Hook System', responsibility: 'Event-based communication between core and plugins without tight coupling', technologies: ['EventEmitter', 'Tapable', 'Custom hooks'] },
    ],
    dataFlow: ['Application starts and core kernel initializes', 'Plugin manager discovers and loads plugins', 'Plugins register hooks and routes', 'Request processed through core with plugin hooks', 'Plugins intercept and modify data at hook points', 'Core aggregates plugin results', 'Response returned with plugin contributions'],
    stateManagement: 'Core manages global state; plugins maintain their own isolated state; shared state accessed through core APIs',
    authentication: 'Authentication provided as a core plugin; other plugins can extend auth with additional providers',
    errorHandling: 'Plugin errors isolated from core; failed plugins disabled without affecting system; error hooks allow plugins to add custom error handling',
    scalability: 'Plugins can be loaded/unloaded dynamically; lazy loading of plugins based on demand; plugin-specific caching strategies',
    deploymentModel: 'Core deployed as base; plugins deployed independently or bundled; plugin marketplace for distribution',
    pros: ['Highly extensible without modifying core code', 'Third-party developers can add functionality', 'Features can be enabled/disabled per deployment', 'Core remains stable while plugins evolve'],
    cons: ['Plugin API design is critical and hard to change', 'Version compatibility between plugins can be challenging', 'Security concerns with third-party plugins', 'Performance impact from hook execution overhead'],
  },
  {
    id: 'pipe-and-filter',
    name: 'Pipe and Filter',
    description: 'Data flows through a series of processing stages (filters) connected by pipes. Each filter performs a specific transformation on the data stream, enabling composable data processing pipelines.',
    keywords: ['pipeline', 'filter', 'stream', 'transform', 'data-processing', 'etl', 'composable'],
    suitableFor: ['Data processing and ETL pipelines', 'Image or media processing systems', 'Compiler and language processing tools', 'Log analysis and monitoring systems'],
    complexity: 'medium',
    folderStructure: {
      'src/pipes/': ['async-pipe.ts', 'buffered-pipe.ts', 'broadcast-pipe.ts'],
      'src/filters/': ['parse-filter.ts', 'validate-filter.ts', 'transform-filter.ts', 'enrich-filter.ts', 'output-filter.ts'],
      'src/pipelines/': ['data-import.ts', 'report-generation.ts', 'log-processing.ts'],
      'src/sources/': ['file-source.ts', 'api-source.ts', 'stream-source.ts'],
      'src/sinks/': ['database-sink.ts', 'file-sink.ts', 'api-sink.ts'],
      'src/core/': ['pipeline-builder.ts', 'filter-registry.ts', 'types.ts'],
    },
    layers: [
      { name: 'Source Layer', responsibility: 'Ingest data from various input sources into the pipeline', technologies: ['File readers', 'API clients', 'Stream consumers'] },
      { name: 'Filter Layer', responsibility: 'Process, transform, validate, and enrich data as it flows through', technologies: ['TypeScript', 'Node.js Streams', 'Transform streams'] },
      { name: 'Pipe Layer', responsibility: 'Connect filters and manage data flow between processing stages', technologies: ['Node.js Pipes', 'RxJS', 'AsyncIterator'] },
      { name: 'Sink Layer', responsibility: 'Output processed data to final destinations', technologies: ['PostgreSQL', 'S3', 'Elasticsearch'] },
    ],
    dataFlow: ['Data ingested from source', 'First filter parses raw input', 'Validation filter checks data integrity', 'Transform filter converts data format', 'Enrichment filter adds computed fields', 'Aggregation filter groups results', 'Output filter writes to sink', 'Pipeline reports completion metrics'],
    stateManagement: 'Filters are stateless transformations; pipeline state tracked by orchestrator; checkpointing for resumable pipelines',
    authentication: 'Authentication handled at source and sink endpoints; pipeline execution authorized at orchestration level',
    errorHandling: 'Failed records routed to error pipeline; filters implement retry logic; dead letter queue for unprocessable records; circuit breaker on external sinks',
    scalability: 'Filters can run in parallel across partitioned data; pipeline stages can be distributed across workers; backpressure prevents memory overflow',
    deploymentModel: 'Pipeline definitions deployed as configurations; filter implementations deployed as worker processes or serverless functions',
    pros: ['Highly composable and reusable filter components', 'Easy to add, remove, or reorder processing stages', 'Natural parallelism at filter and data level', 'Each filter is independently testable'],
    cons: ['Overhead from data serialization between filters', 'Not suitable for interactive or request-response patterns', 'Complex error handling across pipeline stages', 'Debugging data flow through multiple filters is difficult'],
  },
  {
    id: 'service-oriented',
    name: 'Service-Oriented Architecture (SOA)',
    description: 'Application composed of reusable services that communicate through a standardized protocol. Services are coarser-grained than microservices and often share an enterprise service bus.',
    keywords: ['soa', 'service-oriented', 'enterprise', 'esb', 'reusable-services', 'integration', 'wsdl'],
    suitableFor: ['Enterprise integration across multiple systems', 'Organizations with diverse technology stacks to integrate', 'Applications requiring service reuse across business units', 'Legacy system modernization'],
    complexity: 'complex',
    folderStructure: {
      'services/customer-service/': ['service.ts', 'contract.ts', 'repository.ts', 'types.ts'],
      'services/order-service/': ['service.ts', 'contract.ts', 'repository.ts', 'types.ts'],
      'services/inventory-service/': ['service.ts', 'contract.ts', 'repository.ts', 'types.ts'],
      'esb/': ['router.ts', 'transformer.ts', 'orchestrator.ts', 'config.ts'],
      'contracts/': ['customer.wsdl', 'order.wsdl', 'inventory.wsdl', 'shared-types.xsd'],
      'gateway/': ['api-gateway.ts', 'auth.ts', 'rate-limiter.ts'],
      'monitoring/': ['health-checks.ts', 'metrics.ts', 'alerts.ts'],
    },
    layers: [
      { name: 'Consumer Layer', responsibility: 'Client applications that consume services through the service bus', technologies: ['Web Apps', 'Mobile Apps', 'Partner APIs'] },
      { name: 'Service Bus', responsibility: 'Route, transform, and orchestrate messages between services', technologies: ['MuleSoft', 'Apache ServiceMix', 'WSO2'] },
      { name: 'Service Layer', responsibility: 'Coarse-grained services implementing business capabilities with defined contracts', technologies: ['Express', 'Java Spring', 'SOAP', 'REST'] },
      { name: 'Data Layer', responsibility: 'Shared or service-specific data stores', technologies: ['PostgreSQL', 'Oracle', 'SQL Server'] },
    ],
    dataFlow: ['Consumer sends request to service bus', 'ESB routes request to appropriate service', 'ESB transforms message format if needed', 'Service processes business logic', 'Service accesses data store', 'Response transformed and routed back through ESB', 'Consumer receives standardized response'],
    stateManagement: 'Services maintain their own state; ESB manages orchestration state for composite operations; shared data through canonical data model',
    authentication: 'Centralized identity provider with token-based authentication; ESB enforces security policies',
    errorHandling: 'ESB provides centralized error handling and routing; services define fault contracts; compensation transactions for failed orchestrations',
    scalability: 'Services scale independently; ESB can become bottleneck requiring clustering; caching at ESB and service level',
    deploymentModel: 'Services deployed independently on application servers; ESB deployed as centralized middleware; shared infrastructure for monitoring',
    pros: ['Service reuse across multiple applications and teams', 'Standardized integration patterns', 'Centralized governance and monitoring through ESB', 'Technology-agnostic service contracts'],
    cons: ['ESB can become a single point of failure and bottleneck', 'Higher complexity than monolith with more overhead', 'Service granularity is difficult to get right', 'Vendor lock-in with ESB products'],
  },
  {
    id: 'peer-to-peer',
    name: 'Peer-to-Peer Architecture',
    description: 'Decentralized architecture where each node acts as both client and server. Nodes communicate directly without a central coordinating server, sharing resources and responsibilities equally.',
    keywords: ['p2p', 'peer-to-peer', 'decentralized', 'distributed', 'mesh', 'blockchain', 'dht'],
    suitableFor: ['File sharing and content distribution', 'Real-time communication applications', 'Decentralized applications and blockchain', 'Edge computing and IoT networks'],
    complexity: 'complex',
    folderStructure: {
      'src/node/': ['peer.ts', 'connection-manager.ts', 'discovery.ts', 'identity.ts'],
      'src/protocol/': ['message-types.ts', 'handshake.ts', 'routing.ts', 'serialization.ts'],
      'src/network/': ['transport.ts', 'nat-traversal.ts', 'relay.ts', 'dht.ts'],
      'src/storage/': ['local-store.ts', 'distributed-hash.ts', 'replication.ts'],
      'src/consensus/': ['voting.ts', 'conflict-resolution.ts', 'sync.ts'],
      'src/api/': ['local-api.ts', 'admin.ts', 'metrics.ts'],
    },
    layers: [
      { name: 'Network Layer', responsibility: 'Peer discovery, connection management, and NAT traversal', technologies: ['WebRTC', 'libp2p', 'WebSocket', 'TCP'] },
      { name: 'Protocol Layer', responsibility: 'Message format, routing, and communication protocols between peers', technologies: ['Protocol Buffers', 'MessagePack', 'Custom protocols'] },
      { name: 'Consensus Layer', responsibility: 'Agreement on shared state, conflict resolution, and data consistency', technologies: ['CRDT', 'Raft', 'PBFT', 'Gossip protocols'] },
      { name: 'Application Layer', responsibility: 'Business logic running on each peer node', technologies: ['TypeScript', 'Node.js', 'Rust'] },
      { name: 'Storage Layer', responsibility: 'Local data persistence and distributed hash table management', technologies: ['LevelDB', 'IPFS', 'SQLite'] },
    ],
    dataFlow: ['Peer discovers network through bootstrap nodes', 'Connection established via NAT traversal', 'Peer announces available resources to network', 'Request routed through DHT to closest peer', 'Data transferred directly between peers', 'Consensus protocol validates data integrity', 'Local storage updated with received data', 'Replication ensures data availability'],
    stateManagement: 'Each peer maintains local state; shared state synchronized through CRDTs or consensus protocols; eventual consistency across the network',
    authentication: 'Public-key cryptography for peer identity; challenge-response authentication during handshake; reputation systems for trust',
    errorHandling: 'Peers handle disconnections gracefully with automatic reconnection; data integrity verified through hash checks; redundancy through replication across peers',
    scalability: 'Naturally scales as more peers join the network; no central bottleneck; network capacity grows with participants',
    deploymentModel: 'Each peer is an independent deployment; bootstrap nodes provide initial network entry; no central server required for operation',
    pros: ['No single point of failure or central server', 'Scales naturally with number of participants', 'Resilient to network partitions and node failures', 'Reduced infrastructure costs with shared resources'],
    cons: ['Complex NAT traversal and connectivity challenges', 'Data consistency and ordering are difficult', 'Security challenges with untrusted peers', 'Higher latency than centralized systems'],
  },
];
